services:
  web:
    image: amineelgaini/online-shop
    build:
      context: .
      target: production
    ports:
    - "3000:3000"
    environment:
      NODE_ENV: production
      VITE_API_URL: http://localhost:8000